version: '3'

services:
  runner:
    image: github-action-runner-php
    build: .
    environment:
      - ORGANIZATION=devdicas
      - ACCESS_TOKEN=8e69339dfc3f1181d7f925289de3191a62447906
    scale: 10
