version: '3'

services:
  runner:
    image: github-action-runner-php
    build: .
    environment:
      - ORGANIZATION=${ORGANIZATION}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
    scale: ${NUMBER_OF_RUNNERS}
